# Generated by Django 5.2.1 on 2025-05-29 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa'), ('mayorista', 'Mayorista')], default='particular', max_length=20)),
                ('descuento_especial', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
