# Generated by Django 5.2.1 on 2025-06-02 05:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre completo del cliente o empresa', max_length=100)),
                ('telefono', models.CharField(db_index=True, help_text='Teléfono único del cliente', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email del cliente (opcional pero recomendado)', max_length=254)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del cliente')),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa'), ('mayorista', 'Mayorista')], db_index=True, default='particular', help_text='Tipo de cliente para aplicar descuentos y políticas', max_length=20)),
                ('descuento_especial', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento automático (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0, message='El descuento no puede ser negativo'), django.core.validators.MaxValueValidator(100.0, message='El descuento no puede ser mayor a 100%')])),
                ('fecha_registro', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha en que se registró el cliente')),
                ('ultima_compra', models.DateTimeField(blank=True, help_text='Fecha de la última compra realizada', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Si está activo, aparecerá en las listas de selección')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó el cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['tipo_cliente', 'activo'], name='clientes_cl_tipo_cl_a7fdb8_idx'), models.Index(fields=['-fecha_registro'], name='clientes_cl_fecha_r_483ee3_idx'), models.Index(fields=['activo', '-ultima_compra'], name='clientes_cl_activo_18d6ed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('descuento_especial__gte', 0), ('descuento_especial__lte', 100)), name='descuento_valido'), models.UniqueConstraint(fields=('telefono',), name='telefono_unico'), models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='email_unico_no_vacio')],
            },
        ),
    ]
