# Generated by Django 5.2.1 on 2025-06-02 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('concepto', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='VentaDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito')], max_length=20)),
                ('pagado', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas Directas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('salida_venta', 'Salida (Venta Directa)')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_nueva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=200)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
                ('venta_directa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.ventadirecta')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaDirecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='finanzas.ventadirecta')),
            ],
        ),
    ]
