# Generated by Django 5.2.1 on 2025-05-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tiempo_estimado_horas',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tiempo_real_horas',
        ),
    ]
