# Generated by Django 5.2.1 on 2025-06-02 05:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('marca', models.CharField(blank=True, db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'), models.Index(fields=['categoria', 'nombre'], name='inventario__categor_b7fe87_idx'), models.Index(fields=['cantidad_actual', 'stock_minimo'], name='inventario__cantida_649dc1_idx'), models.Index(fields=['-fecha_creacion'], name='inventario__fecha_c_8516a7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_venta__gt', models.F('precio_compra'))), name='precio_venta_mayor_que_compra'), models.CheckConstraint(condition=models.Q(('cantidad_actual__gte', 0)), name='cantidad_actual_no_negativa'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='stock_minimo_no_negativo')],
            },
        ),
    ]
