# Generated by Django 5.2.1 on 2025-05-29 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_prometida', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('tipo_bordado', models.CharField(choices=[('computarizado', 'Computarizado'), ('manual', 'Manual'), ('combinado', 'Combinado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('especificaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_diseno', 'En Diseño'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_real_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adelanto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notas_internas', models.TextField(blank=True)),
                ('archivo_diseno', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
    ]
